export enum HtmlTemplate {
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  SUBMITTED = 'SUBMITTED',
  PRE_SUBMISSION_ERROR = 'PRE_SUBMISSION_ERROR',
  POST_SUBMISSION_ERROR = 'POST_SUBMISSION_ERROR',
  ERROR_RESOLVED = 'ERROR_RESOLVED',
  REMINDER_SUBMIT = 'REMINDER_SUBMIT',
  REMINDER_RESUBMIT = 'REMINDER_RESUBMIT',
  REMINDER_STATE = 'REMINDER_STATE',
  NON_COMPLETION_SURVEY = 'NON_COMPLETION_SURVEY',
}
